[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "onichan"
authors = [{name = "Eymen", email = "rbstsoul@gmail"}]
dynamic = ["version", "description"]
